### PR TITLE
Fix(engine): handle transaction gas limit properly

### LINKED ISSUE #119: Correctly handle gas limits on transactions
Presently we allow any gas limit to be specified on a transaction passed to `submit`. This is incorrect behaviour relative to Ethereum where there is a notion of "intrinsic gas".

The current behaviour is causing a problem because (a) it is an incompatibility with Ethereum, and we are always pushing for maximum compatibility; and (b) the relayer has trouble handling transactions with 0 gas limit (and these would be invalid transactions if we had the correct logic in the Engine).

This issue is completed when the following is done:

- [ ] Have a function which computes "intrinsic gas" for transactions
- [ ] Verify all transactions passed via `submit` have a gas limit greater than or equal to the intrinsic gas
- [ ] Respect the gas limit when processing transactions passed to `submit` (i.e. fail with OOG when computation exceeds limit)

References:

* https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L259
* https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L114
* https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L593

### PR DESCRIPTION
**Pull request by birchmd**
Fixes #119

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -239,16 +239,30 @@ mod contract {
...
+                if signed_transaction.transaction.gas < intrinsic_gas.into() {
+                    sdk::panic_utf8(b"ERR_INTRINSIC_GAS")
+                }
+            }
+        }
+
         // Figure out what kind of a transaction this is, and execute it:
         let mut engine = Engine::new_with_state(state, sender);
         let value = signed_transaction.transaction.value;
+        let gas_limit = u256_to_u64(signed_transaction.transaction.gas);
```
Comment (birchmd) [inline src/lib.rs:258]: I'm not sure if this is correct behavior or not. Presently it is taking the gas limit mod `u64::MAX + 1` to make it fit into `u64` (since that is the type expected by SputnikVM). But should I panic if the gas limit is larger than `u64::MAX` instead of silently ignoring the larger number? Or maybe I should truncate to `u64::MAX` in the case it is larger? Is there an Ethereum spec for this?

File: src/engine.rs [hunk 2]
```diff
@@ -382,15 +387,15 @@ impl Engine {
         value: Wei,
         input: Vec<u8>,
     ) -> EngineResult<Vec<u8>> {
-        let mut executor = self.make_executor();
+        let mut executor = self.make_executor(u64::MAX);
```
Comment (birchmd) [inline src/engine.rs:390]: Do view calls need a gas limit?

**Review by birchmd — COMMENTED** [review]
Some clarifying questions:

File: src/engine.rs (hunk 2 above)
Comment (artob) [reply src/engine.rs:390]: Yes, for compatibility with mutative calls, a gas limit is passed in: https://eth.wiki/json-rpc/API#eth_call

File: src/lib.rs [hunk 3]
```diff
@@ -276,6 +290,7 @@ mod contract {
             meta_call_args.contract_address,
             meta_call_args.value,
             meta_call_args.input,
+            u64::MAX, // TODO: is there a gas limit with meta calls?
```
[the remark this answers is not in the document]
Comment (artob) [reply src/lib.rs:293]: We're not at all using the meta-transaction machinery at the moment, so it's fine to leave it as you did, with a `TODO` comment.

File: src/lib.rs (hunk 1 above)
Comment (artob) [reply src/lib.rs:258]: Gas limits are `uint64` throughout the Geth code base, so there's no way it can handle a larger value. However, I'm unsure what Geth does if receiving a transaction with a larger value. I'll endeavor to find out and come back to you.

Comment (artob) [reply src/lib.rs:258]: Specifying the same max gas limit with another endpoint implementation:

`{'code': -32000, 'message': 'exceeds block gas limit'}`

Comment (artob) [reply src/lib.rs:258]: Looks like Geth specifies the error code `ErrGasUintOverflow` (`gas uint64 overflow`) for situations where the gas would overflow:

https://github.com/ethereum/go-ethereum/blob/master/core/error.go#L64

We probably ought to define a corresponding error code for this, so that we can return the corresponding error message in the relayer, for full Geth compatibility.

Comment (birchmd) [reply src/lib.rs]: Made to panic if gas limit is larger than `u64::MAX` in https://github.com/aurora-is-near/aurora-engine/pull/123/commits/57934d44cf42e8e2ecbbd4d32508c83175441d65

File: src/engine.rs (hunk 2 above)
Comment (birchmd) [reply src/engine.rs]: Gas limit added to `Engine::view` in https://github.com/aurora-is-near/aurora-engine/pull/123/commits/b8879c8dd53cb2c8b542180432d55003158e69ab but it's not really used yet because the only way `view` is called is from `view_with_args` which does not have a gas limit (since it is Near-native). However, we will add an `eth_call` contract method in the future which will pass a user-input gas limit to `Engine::view`.

**Review by joshuajbouw — APPROVED** [review]
Straight forward

**Review by sept-en — APPROVED** [review]
LGTM!

**Review by artob — APPROVED** [review]
LGTM :+1: Great work, @birchmd. The only thing that stuck out is that we might better define a max gas constant instead of using `u64::MAX` all over the place, but we can address that later.
